baseurl = "https://ddorn.gitlab.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Le blog de Diego"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"

[Params]
  subtitle = "Un peu de tout, c'est à dire des maths, de l'info, principalement."
  logo = "lama.png"
  favicon = "lama-trans.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  useHLJS = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Diego Dorn"
  youtube = "channel/UCN0kVAIU46vvM86CoGtW1Lw" # or channel/channelname
  itchio = "cozyfractal"
  gitlab = "ddorn"
  twitter = "CozyFractal"
  github = "ddorn"
  reddit = "diegodorn"
  instagram = "corsica4ever"
  linkedin = "diego-dorn-56389a1b2"
  email = "diego-blog@lama-corp.space"

  # soundcloud = ""
  # spotify = ""
  # bandcamp = ""
  # keybase = ""
  # facebook = ""
  # googleplus = "" # or xxxxxxxxxxxxxxxxxxxxx
  # xing = ""
  # stackoverflow = ""
  # snapchat = ""


[[menu.main]]
    name = "Posts"
    url = "post"
    weight = 1

[[menu.main]]
    name = "Resources"
    url = "page/resources/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
